urlshorten/shortener/urls.py
from django.urls import path
from . import views
app_name='shortener'
urlpatterns = [
    path('',views.shorten_url,name='home'),
    path('<short_id>/',views.get_url,name='get_url'),
]

urlshorten/urlshorten/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shortener.urls')),

]

urlshorten/shortener/models.py
from django.db import models

# Create your models here.
class Url(models.Model):
	short_id=models.SlugField(max_length=6,primary_key=True)	
	http_url=models.URLField(max_length=200)
	publish_date=models.DateTimeField(auto_now=True)
	count=models.IntegerField(default=0)
	class Meta:
		verbose_name_plural="Urls"
	def __str__(self):
		return (self.http_url)

# auto_now - 	 updates the value of field to current time and date every time the Model.save() is called.
# auto_now_add - updates the value with the time and date of creation of record.

# URLField is used to store URL, where as SlugField is used to store a alphanumeric/varchar value that relates to the title or some description of the model.
# Example
# URL - https://clipmyurl.herokuapp.com/jvitMr
# slug - jvitMr 

urlshorten/shortener/views.py
from django.shortcuts import render,redirect
from .models import Url
from django.http import HttpResponse
import string,random
from django.conf import settings
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
import re

def shorten_url(request):
	response_data = {}
	if request.method == 'POST':
		http_url=request.POST.get('http_url')
		if request.POST.get('http_url'):
			x = re.search("^http://127.0.0.1:8000/*[a-z 0-9 A-Z]*$", http_url)
			if(x!=None):
				e="Please enter a valid url."
				return render(request=request,template_name='shortener/index.html',context={'response_data':e})
			val = URLValidator()
			try:
				val(http_url)
				try:
					http_url = Url.objects.get(http_url=http_url)
					short_id = http_url.short_id
				except:
					short_id=get_short_code()
					temp=Url(http_url=http_url,short_id=short_id)
					temp.save()
				response_data["f_url"]=http_url		
				response_data["url"]=settings.SITE_URL+"/"+short_id		
				return render(request=request,template_name='shortener/generated.html',context={'short_url':response_data["url"],'full_url':response_data["f_url"]})
			except ValidationError:
				e="Please enter a valid url."
				return render(request=request,template_name='shortener/index.html',context={'response_data':e})
		else:
			e="Please enter a url."
			return render(request=request,template_name='shortener/index.html',context={'response_data':e})
	return render(request=request,template_name='shortener/index.html',context={'response_data':None})

def get_url(request,short_id):
	try:
		temp2=Url.objects.get(pk=short_id)
		url=temp2.http_url
		temp2.count=temp2.count+1
		temp2.save()
		return redirect(url)
	except:
		return HttpResponse("<h1>INVALID REQUEST!!!</h1>")

def get_short_code():
	length=6
	char=string.ascii_uppercase + string.digits + string.ascii_lowercase
	while True:
		short_id = ''.join(random.choice(char) for x in range(length))
		try:
			temp1=Url.objects.get(pk=short_id)
		except:
			return short_id

#Some useful links
#http://www.learningaboutelectronics.com/Articles/How-to-insert-data-into-a-database-from-an-HTML-form-in-Django.php/
#url validation - https://stackoverflow.com/questions/7160737/python-how-to-validate-a-url-in-python-malformed-or-not

urlshorten/shortener/templates/shortener/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
	  <title>Clip my URL</title>
	  <link rel="icon" href="{% static "img/cmu.png"%}" type="image/icon type">
	  <script type="text/javascript" src="{% static 'javascript/main.js' %}"></script>
</head>
<body style="background-color :#e3e3e3" >
	<div style="margin-bottom:50px">
	<nav style="background-color :#4d6d9a" class="navbar navbar-light " style="margin-bottom:100px">
	  <div class="container-fluid ">
	    <div class="navbar-header">
	      <a class="navbar-brand" style="color: white;" href="{% url 'shortener:home' %}" title="Want to shorten link!">
	      	<span style="font-size:120%;font-family:Verdana,Arial Black; " ><strong>Clip my URL</strong> </span>
	      	<sub><span style="font-size:70% ;font-family:Comic Sans MS ">shortening service</span></sub></a></div></div>
	</nav>
	</div>
	<div class="container">
{% block content %}
  
{% endblock %}
	</div>
	<div class="navbar-light navbar container-fluid" style="background-color :#4d6d9a; color:white; position:absolute; bottom:0px;width:100%; margin-bottom:0px"><br>
	<p><strong>Contact Us At &nbsp&nbsp&nbsp&nbsp- </strong>&nbsp&nbsp&nbsp&nbsp
	<a style="color: white;" href="https://www.linkedin.com/in/piyushkhanna30/"><strong>Linkedin</strong></a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a style="color: white;" href="https://www.twitter.com/PiyushKhanna30"><strong>Twitter</strong></a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a style="color: white;" href="https://www.instagram.com/piyushkhanna_/"><strong>Instagram</strong></a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a style="color: white;" href="https://www.github.com/PiyushKhanna30"><strong>GitHub</strong></a></p>
    <br/>
    <p style="color: white;font-size: 0.9rem;" class="col-6"></strong>© 2019 Piyush Khanna.</strong></p>
  </div>
</body>
</html>

urlshorten/shortener/templates/shortener/generated.html
{% extends "shortener/base.html" %}
{% block content %}
	  <form >
	    <div class="form-group">
	      <label for="sub_url">Submitted URL : </label>
	      <input type="text" class="form-control" id="sub_url" value={{full_url}}/>
	    </div>
	    <div class="form-group">
	      <label for="sho_url">Shorten URL :</label>
	     	<div class="input-group">
				<input type="text" class="form-control" id="sho_url" value={{short_url}}>
				<span class="input-group-btn">
					<a href ={{short_url}}>
						<button class="btn btn-success" type="button">Go!</button>
					</a>
				</span>
		 	</div>
	    </div>
	  </form>
	  <a href ="{% url 'shortener:home' %}"><button style="margin-top:30px" class=" btn btn-success btn-block" type="button">Generate another !</button></a>

{% endblock %}
<!-- disabled="True" -->

urlshorten/shortener/templates/shortener/index.html
{% extends "shortener/base.html" %}
{% block content %}
 

	  <form method="POST" id="theForm" onSubmit="return validateTextbox();">
{% csrf_token %}	  	
	    <div class="form-group">
	      <label for="usr">Enter URL :</label>
	      <input type="url" class="form-control" id="usr" name="http_url" placeholder="https://www.facebook.com" required=True />
	    </div>
	      <button style="margin-top:30px" type="submit" class="btn btn-success btn-block">Generate</button>
	  </form>
	  {% if response_data %}
	    <div style="margin-top:30px" class="alert alert-info">
		    <strong>Info!</strong> {{response_data}}
		</div>
	  {% endif %}   
{% endblock %}